### ISSUE TITLE
Better documentation around aggregations functions

### ISSUE THREAD

**Issue by ndrean** [elixir-nx/nx#1051]
It would be nice to have the formulas used by the functions or a reference to the ones used as most functions don't have. Some sublibraries like Element-wise have explicit formulas, but none in the Aggregate module for example. For example, the aggregation option is mysterious whether in `Nx.mean` or `Nx.argmax` for example, and the examples alone are not enough to understand.

For example, running examples is not enough to understand what the function is doing.
```

t = Nx.tensor(
  [
    [
      [4, 2, 3], [6, -5, 3]
    ], 
    [
      [3, 1, 2], [4, -10, 3]
    ],
    [
      [4,2,4], [3,3,3]
    ]
  ],
  names: [:x, :y, :z]
)
Nx.argmax(t, axis: :y)

#Nx.Tensor<
  s64[x: 3][z: 3]
  [
    [1, 0, 0],
    [1, 0, 1],
    [0, 1, 0]
 ]

Nx.argmax(t, axis: :x)
#Nx.Tensor<
  s64[y: 2][z: 3]
  [
    [0, 0, 2],
    [0, 2, 0]
  ]

Nx.argmax(t, axis: y)
#Nx.Tensor<
  s64[x: 3][z: 3]
  [
    [1, 0, 0],
    [1, 0, 1],
    [0, 1, 0]
 ]
```

**Comment by josevalim** [comment]
I am not sure because [`argmax` in Numpy does not have any formulas either](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) and therefore it is unclear if there is even a readily available formula that we could use.

**Comment by polvalente** [comment]
I don't think mathematical notation for axes aggregation would make things any more clear than the examples.
This is especially so because we can aggregate on any axis or set of axes and don't have a lower nor upper bound on how many axes there are, so I don't see how we can have a clear LaTeX notation for that.

We could instead consider a more "written out" explanation (PRs welcome for consideration/discussion!) for whatever feels confusing.

**Comment by ndrean** [comment]
My remark was general. Most if not all aggregate functions have no reference formula (mean, variance, etc) and I believe a formula is still welcome because we don't know what it does, even if it may seem obvious. But think of statiscal formulas with biais. A formula can be shorter than a literal example in such a case, but both are doable.

I focussed on these aggregates because I needed something like this but it took more than an hour to try to understand `Nx.argmax`. Since I imagine there is an algorithm and not a formula behind it, then indeed for this particular case, a worked example should make things more clear. I only fear that the doc will suddenly explode in terms of length. 


For this particular case of `argmax`, I hope the following will help to understand what it does. The case `argmean` is similar except for the aggregating function of course.

Take an example of a (3,2,3) tensor with the indexing below:

$$
t = 
  \begin{bmatrix}
    \begin{bmatrix}
      [ x_{0,0,0}, & x_{0,0,1}, &x_{0,0,2}], \\
      [ x_{0,1,0}, & x_{0,1,1}, &x_{0,1,2} ]
    \end{bmatrix}, \\
    \\
    \begin{bmatrix}
      [x_{1,0,0}, & x_{1,0,1}, & x_{1,0,2} ], \\
      [x_{1,1,0}, & x_{1,1,1}, & x_{1,1,2} ]
    \end{bmatrix}, \\
    \\
    \begin{bmatrix}
      [ x_{2,0,0}, & x_{2,0,1},& x_{2,0,2} ], \\
      [ x_{2,1,0}, & x_{2,1,1}, & x_{2,1,2} ]
    \end{bmatrix}
  \end{bmatrix}
$$

Note: $\max$ below means the "index of the biggest value"

Aggregate on the $x$ axis:  you fix $j$ and $k$ and find "ind_max" of the $x_{i,j,k}$ with $i$ varying.

$$
  \begin{bmatrix}
  [ \max_i x_{i,0,0}, \max_i x_{i,0,1}, \max_i x_{i,0,2}] \\
  [ \max_i x_{i,1,0}, \max_i x_{i,1,1}, \max_i x_{i,1,2}]
  \end{bmatrix}
$$

Aggregate on the $y$ axis: you fix $i$ and $k$ and find "ind_max" of the $x_{i,j,k}$ with $j$ varying.

$$
\begin{bmatrix}
[ \max_j x_{0,j,0}, \max_j x_{0,j,1}, \max_j x_{0,j,2}], \\
[ \max_j x_{1,j,0}, \max_j x_{1,j,1}, \max_j x_{1,j,2}], \\
[ \max_j x_{2,j,0}, \max_j x_{2,j,1}, \max_j x_{2,j,2}];
\end{bmatrix}
$$

Aggregate on the $z$ axis: you fix $i$ and $j$ and find "ind_max" of the $x_{i,j,k}$  with $k$ varying (the inner vector):

$$
\begin{bmatrix}
[ \max_k x_{0,0,k}, \max_k x_{0,1,k}], \\
[ \max_k x_{1,0,k}, \max_k x_{1,1,k}], \\
[ \max_k x_{2,0,k}, \max_k x_{2,1,k}];
\end{bmatrix}
$$

A worked example using the formulas above:

```
t = Nx.tensor(
  [
    [
      [4, 2, 3], 
      [6, -5, 7]
    ], 
    [
      [3, 1, 2], 
      [7, -10, 3]
    ],
    [
      [4, 2, 4], 
      [3, 3, 3]
    ]
  ],
  names: [:x, :y, :z]
)
```
```
Nx.argmax(t, axis: :x) = 
[
  [ ind_max(4,3,4), ind_max(2,1,2), ind_max(3,2,4) ],
  [ ind_max(6,7,3), ind_max(-5,-10,3), ind_max(7,3,3) ]
  ]
]
=
[
  [ 0,0,2], [1,2,0]
]
```

```
Nx.argmax(t, axis: :y) = 
[
  [
    [ ind_max(4,6), ind_max(2,-5), ind_max(3,7)],
    [ ind_max(3,7), ind_max(1,-10), ind_max(2,3)],
    [ ind_max(4,3), ind_max(2,3), ind_max(4,3)]
  ]
]
=
[
  [
    [1,0,1],
    [1,0,1],
    [0,1,0]
  ]
]
```

```
Nx.argmax(t, axis: :z) = 
[
  [ind_max(4,3,2), ind_max(6,-5,7)],
  [ind_max(3,1,2), ind_max(7,-10,3)],
  [ind_max(4,2,4), ind_max(3,3,3)]
]
=
[
  [0,2],
  [0,0],
  [0,0]
]
```

**Comment by polvalente** [comment]
I kinda like where this is going, but I have an issue with calling this a formula. In the example you're taking the aggregation for each single axis for a 3-dimensional tensor. 

This still doesn't cover how it would work for aggregating on multiple axes, nor does it cover tensors with different dimensionality. And I don't think generalizing the LaTeX notation for different dimensionality would make things more clear, especially if we think about people that don't have a more formal mathematical background.

However, I do like the idea of having a "step-by-step" example with some text explanation for some cases.
This would preferably be done in Elixir code itself instead of LaTeX, kinda like an expansion of the current "Examples" section.

Finally, perhaps there's a way to have a general explanation on how axes aggregation works that would show up at the top of the docs section (cc @josevalim)? This would provide a nice space for a more general guide on how the functions are actually similar, but I'm not sure if ex_doc has this capability yet.

**Comment by josevalim** [comment]
We don't have the feature in ExDoc. But we could add a section on the `@moduledoc` and refer to said header from each aggregation function. Something like "To learn more about aggregations, see the "Aggregations" section in the moduledoc." We can also use anchor tags as links.

**Comment by josevalim** [comment]
@ndrean would you be interested in doing a first contribution to the `@moduledoc` that generally explains how the aggregating axes functions work? You can pick max/argmax/sum as an initial example. Thank you!

**Comment by ndrean** [comment]
Sure, I would be pleased to contribute. I will propose something with a "worked example".

@polvante made a remark: "This still doesn't cover how it would work for aggregating on multiple axes, nor does it cover tensors with different dimensionality."

I still need to understand this point.

**Comment by polvalente** [comment]
> Sure, I would be pleased to contribute. I will propose something with a "worked example".
> 
> @polvante made a remark: "This still doesn't cover how it would work for aggregating on multiple axes, nor does it cover tensors with different dimensionality."
> 
> I still need to understand this point.

> doesn't cover how it would work for aggregating on multiple axes

What I meant is that your worked example only shows the intuition for how aggregation works over a single axis.
We would need to expand on that idea for multi-axis aggregation as well.

> nor does it cover tensors with different dimensionality

The worked example works on a 3D tensor only. It might be more didactic to introduce the idea over a rank 1 tensor, expand to rank 2 and then to rank N.

**Comment by ndrean** [comment]
Isn't multi axis just a piping of aggregations?

**Comment by polvalente** [comment]
> Isn't multi axis just a piping of aggregations?

I was going to say it is, but I don't think that's the case for standard_deviation.

I'm currently out, so I can't test this, but I'd expect that for a tensor [[0, 1], [2, 3]] we would get:

standard_deviation over axes: [0] = [1, 1]
standard_deviation over axes: [1] = [0.5, 0.5]

standard_deviatoon over axes: [0, 1] =~ 1.118

If it were analogous to piping, the result would be 0 because the standard deviation over any of the 2 axis is a constant tensor (and thus all elements equal the mean).

I tend to think of aggregating over multiple axes as if they were all flattened into a single axis before the calculation is performed. This can indeed be implemented as a piping over the axes for most operations, though, but it's not always the case.

**Comment by ndrean** [comment]
Yes I see

**Comment by ndrean** [comment]
I also checked `numpy.std()` for a matrix (non-square of course), and they flatten too.

**Comment by polvalente** [comment]
Regarding argmin/argmax: We could return the "fully-qualified" index [x0, x1, ..., xn] (for a (N+1)D tensor), but I think the linear index is used instead for compatibility with Jax

Regarding standard_deviation: For me it worked fine. Make sure you're passing the axes in a list because it has the `:axes` option instead of `:axis`.

**Comment by polvalente** [comment]
Ok, so I've just seen your edit. Answer below:

> You mean: vector, then matrix, then 3D...
> 
> Isn't multi axis just a piping of aggregations?

As discussed above, it is not, altough most cases could implement it as such.

> Say a 4D tensor (i,j,k,l), you aggregate the second j, you can write a formula:
> 
> $\rm{argmin}_j = \min(\rm{tensor}[i, j, k, l],  j \in [0,I])$
> 
> and then pipe along k if you selected the last.

For argmin specifically we don't support multi-axes. However, it's even easier than it is easier to see with standard_deviation to see what would happen if it were implemented as a pipe over each axis instead of a simultaneous aggregation over the whole tensor for the case where no axis is passed:

For a tensor `x = Nx.tensor([[3, 2], [1, 0]])` we would have:

`Nx.argmin(x, axis: 0)` = `Nx.argmin(x, axis: 1)` = `Nx.tensor([1, 1])`. With the default `tie_break: low`, piping would result in `Nx.tensor(0)`, because we're now getting indices over the first aggregation axis instead of the values. Note that if the tensor were `Nx.tensor([[0, 1], [2, 3]])` the result would be correct, but that's just a coincidence. `tie_break: :high` would also yield incorrect results here for both example tensors.

If we considered the whole set, however (which happens if `axis: nil`), we get `Nx.tensor(3)` as a result, as expected.

As a final observation, I think using argmin/argmax as examples isn't the best idea because we only support single-axis or full-tensor aggregation for those.

**Comment by ndrean** [comment]
What do you think of a companion Livebook?

**Comment by polvalente** [comment]
I don't think a livebook would hurt, but I think we should start with a standard format doc.

Re commutativity: that's because multi-axes aggregation happens simultaneously, as discussed above. It doesn't make sense to think about commutativity for something that doesn't have a sequence. 

The easiest intuition is to think about transposing all aggregation axes to the end of the tensor and then flattening them into a single axis.

**Comment by ndrean** [comment]
ok. 
I said that because I quickly tried to find how `argmin` or similar was coded, and I didn't see any kind of algorithm or at least didn't understand. Still amazed by the quantity of work done here. 

Anyway, If you agree,  I will continue and simply go on with some worked - visual - examples. Gather together in one example -as  suggested by JoseV - for things that work similarly like `argmin`, `argmax`, `mean`  for single-axis jobs, include the "keep", and then (if I understand) other examples for mutlti-axis reduction where it makes sense or is coded.

**Comment by polvalente** [comment]
Sounds like a good plan!

**Comment by ndrean** [comment]
It is not the moduldoc form but just in a livebook form, simply because it is easier to read and interact with I believe. Let me know if this is more or less in line with your expectations.

[![Run in Livebook](https://livebook.dev/badge/v1/blue.svg)](https://livebook.dev/run?url=https%3A%2F%2Fgithub.com%2Fndrean%2Fdraft_elixir_nx_agg_doc%2Fblob%2Fmain%2Fmodoc_agg_nx_01.livemd)

**Comment by josevalim** [comment]
@ndrean looks great to me and at this point I am convinced we should rather keep it as a guide. The `Nx` docs page already takes forever to load and adding formulas and diagrams will make it heavier. Plus it is about time we have more guides for Nx itself :)

Just one note, at one point you have a large tensor define inline, consider doing this:

```

iex(1)> import Nx, only: :sigils
Nx
iex(2)> ~V[1 2 3 4 5 6]
#Nx.Tensor<
  s64[6]
  [1, 2, 3, 4, 5, 6]
>
```

it will be a tiny bit less verbose. The import can happen at the top!

**Comment by ndrean** [comment]
Yes, I don't believe this should be added to the doc like this as it would become unreadable. IMO it is just a guide, not replacing anything but I hope this sheds some light on what is going on.

Noted for the sigils.

Then, what should I do with this? The Livebook format was just to be easily readable.  Also, the English style might need to be corrected by a "native" :)

 `Plus it is about time we have more guides for Nx itself :)`

If you accept reading my modest opinion, definitely yes. And centralised. But what exactly? Well, besides the "how to use Nx", my first question is what is the point of a Python "metoo"? I am not at all judging the quality of the amazing work already done. My concern was beside some potential integration with Elixir web apps, what is bringing Nx to the world? I don't believe that the BEAM is good at calculus. I vaguely understand that you can support some backends. Are you delegating calculus to a third party? Are you saying that thanks to the BEAM distribution you can parallelise?  As a noob, I was asking for a better understanding of why to adopt Nx. Even before reading a "how to", I felt a "why" guide would make sense, and probably a lot of people may have too. Thanks for having taken time to read this.

**Comment by josevalim** [comment]
> Then, what should I do with this? 

Can you please PR it in? Then we will review and do a couple passes later. :)

I am hoping many of those answers will be covered in the README. In a nutshell: yes, we have compilers that compile Nx code to efficient CPU and GPU code. :) like 3 to 5 orders of magnitude faster! If you feel something is missing, feel free to ask and/or send PRs. :)

**Comment by josevalim** [comment]
Closing in favor of PR!
