### ISSUE TITLE
Nx.LinAlg.eigh produces strange results

### ISSUE THREAD

**Issue by samuelmanzanera** [elixir-nx/nx#1076]
Hello

I try to use eigenvalues decomposition in Nx.
However, I'm facing some issues regarding the results.
I did a comparison with NumPy and the results aren't the same.

```elixir
iex> Nx.tensor([[0, 2], [2, 3]]) |> Nx.LinAlg.eigh()
{#Nx.Tensor<
   f32[2]
   [3.999980926513672, -0.9999809265136719]
 >,
 #Nx.Tensor<
   f32[2][2]
   [
     [0.4454658031463623, 0.895298957824707],
     [0.895298957824707, -0.4454658031463623]
   ]
 >}
```

```python
>>> import numpy as np
>>> from numpy.linalg import eigh

>>> a = np.array([[0, 2], [2, 3]])
>>> eigh(a)
(array([-1.,  4.]), array([[-0.89442719,  0.4472136 ],
       [ 0.4472136 ,  0.89442719]]))
```

**Comment by msluszniak** [comment]
Yeah, is because the implementation in binary backend is broken and we will reimplement it. However, if you set backend as EXLA you will get thr correct results.

**Comment by msluszniak** [comment]
And that's why svd in binary backend generate different results than correct one, because svd uses eigh in binary backedn implementation.

**Comment by polvalente** [comment]
The results are mathematically the same. Notice that Nx outputs 4 and -1 as eigenvalues, aside from rounding errors.
The first eigenvector, corresponding to 4 is [0.4454, 0.8952] and the other, corresponding to -1 is [0.8952, -0.4454].

For numpy, the order of the eigenvalues is switched, with -1 coming first. The eigenvector for -1 is [-0.8944, 0.4472] and the one for 4 is [0.4472, 0.8944]. Discounting rounding errors again, these are basically the same, with the minor difference that the sign for the eigenvector for -1 is also switched.

However, an eigenspace is only guaranteed to be unique up to a sign -- which is easy to see because a given vector [a, b] is in the same direction as a vector [-a, -b] and the only requirement is that each proper eigenvector has it's own linearly independent direction.

What @msluszniak pointed out is also relevant, but it's important to highlight these main behaviours of eigendecomposition and SVD in general.

**Comment by msluszniak** [comment]
@polvalente I mean in this particular case indeed there are no diverged results. 

But for this matrix
 [[ 0.05477347, -0.33786303,  0.10690729, -0.02246768],
        [-0.33786303,  0.29224722,  0.26443713,  0.33520083],
        [ 0.10690729,  0.26443713,  0.07571281,  0.02051978],
        [-0.02246768,  0.33520083,  0.02051978,  0.09305623]]
we got in Nx
 {#Nx.Tensor<
    f32[4]
    [0.7275585532188416, -0.40110692381858826, 0.17198389768600464, 0.017355527728796005]
  >,
  #Nx.Tensor<
    f32[4][4]
    [
      [0.35916027426719666, -0.5357038974761963, -0.6361281275749207, 0.42369478940963745],
      [-0.7836878299713135, -0.6060684323310852, -0.02153218351304531, -0.1344778835773468],
      [-0.2672005295753479, 0.4525536000728607, -0.7711756825447083, -0.35918542742729187],
      [-0.43062877655029297, 0.3753633499145508, -0.012862256728112698, 0.8205999135971069]
    ]
  >}
vs in jax
 (DeviceArray([-0.40120745,  0.01702507,  0.17235827,  0.7276138 ], dtype=float32),
  DeviceArray([[ 0.5389725 ,  0.39385098, -0.6501477 ,  0.36290246],
               [ 0.6116504 , -0.1352644 , -0.00994076, -0.77941555],
               [-0.44395748, -0.39439   , -0.7578279 , -0.2702879 ],
               [-0.37187913,  0.8191714 , -0.05391173, -0.43331048]],            dtype=float32))

**Comment by polvalente** [comment]
@msluszniak Those still fall in the same categories of rounding-error (they are mostly correct to 2 decimal places I think, 1 for sure) and sign switch. Note that this matrix is specifically tricky because it's eigenvalues are really close, and due to XLA's and BinaryBackend's eigh speed we're limiting the number of iterations for eigh on all backends by default, which explains these errors.
