### ISSUE TITLE
Issue with EXLA.jit on LinReg example

### ISSUE THREAD

**Issue by meanderingstream** [elixir-nx/nx#1091]
I was exploring the Nx examples/regression.exs code in a notebook in order to understand using the grad function.  I found an issue where the loss function, MSE, was not being calculated correctly because of mismatched shapes.  I was able to get the notebook to work in Torchx and then decided to try to perform a pull request for the regression.exs.  When I tried to implement the EXLA version, I ran into errors.  The cell with the train function call would process for a while, 120 seconds or so, and then pop up an error message.  "Runtime node terminated unexpectedly - no connectionRuntime node terminated unexpectedly - no connection" when jit function was used.

The 120 seconds is longer than the ~70 seconds when default_backend specifies the GPU.  This seemed like strange behavior that I should share with the team.

The notebooks that can be used to repeat the issue are at:  https://github.com/meanderingstream/problem_notebooks

Summary:
LineReg.exla.v1.livemd -- Fails, uses EXLA/GPU default_backend and jit
LinReg.exla.v2.livemd -- Succeeds, uses just EXLA/GPU default_backend and no jit
LinReg.exla.v2.livemd -- Fails, doesn't use default_backend but uses jit
LinReg.torch.livemd -- Succeed using Torch

I am currently using a 3080 10G GPU

**Comment by josevalim** [comment]
@meanderingstream the node is running out of memory and then it loses connection. :)

The reason why this happens is because you are inlining the computation of all _100_ epochs into a single jit expression:

    EXLA.jit(&LinReg.train/3).(params, epochs_list, lin_fn)

This means we build a massive tree to compile to the GPU, which takes a long time until exhausting resources.

What you probably want to do is something like this:

    LinReg.train(params, epochs_list, lin_fn)

Given `update/4` is already a defn, that should be compiled and inlined accordingly.
