### ISSUE TITLE
Support vmap

### ISSUE THREAD

**Issue by josevalim** [elixir-nx/nx#174]
See the tensorflow feature and linked paper: https://www.tensorflow.org/api_docs/python/tf/vectorized_map

**Comment by josevalim** [comment]
Note: our goal is not to implement this as a transform, but instead as part of the named axes.

**Comment by josevalim** [comment]
Related: https://colab.research.google.com/drive/1BsVkddtVMX35aZAvo2GyI-wSFPVBCWuA

**Comment by josevalim** [comment]
We need to add batching to eye/2.

**Comment by josevalim** [comment]
Another one: https://github.com/mcabbott/Tullio.jl

**Comment by polvalente** [comment]
vmap implementation proposal:

## Interface

The main idea is to fully separate what we currently call batch axes from the rest of the tensor's shape.
For instance, we could vectorize a tensor like so:

```elixir
t = Nx.iota({10, 2, 3})
vec = vectorize(t, :custom_axis_name)
#Nx.Tensor<
  vectorized [custom_axis_name: 10]
  s64[2][3]
  [
    0, 1, 2
    3, 4, 5
  ]
  [
    6, 7, 8
    9, ...
  ]
  ...
>
```

This vectorized tensor can then be operated against other vectorized tensors.

If the vectorized axis has the same name, operations happen normally:

```elixir
vec + vec
#Nx.Tensor<
  vectorized [custom_axis_name: 10]
  s64[2][3]
  [
    0, 2, 4
    6, 8, 10
  ]
  [
    12, 14, 16
    18, ...
  ]
  ...
>
```

An operation against a non-vectorized tensor just broadcasts the non-vectorized tensor in a similar fashion to what happens when scalars are operated against tensors:

```elixir
non_vec = Nx.tensor([[3, 3, 3], [0, 0, 0]])
vec + non_vec
#Nx.Tensor<
  vectorized [custom_axis_name: 10]
  s64[2][3]
  [
    3, 4, 5
    3, 4, 5
  ]
  [
    9, 10, 11
    9, ...
  ]
  ...
>
```

Operations against a vectorized tensor that has a different vectorized axis name will result in a compound tensor with two vectorized axes:

```elixir
t = Nx.iota({2, 2, 2})
vec = vectorize(t, :this)
t2 = Nx.tensor([
    [
        [1, 1], 
        [1, 1]
    ],
    [
        [-1, -1],
        [-1, -1]
    ]
])

vec2 = vectorize(t2, :that)

vec * vec2 
#Nx.Tensor<
  vectorized [this: 2][that: 2]
  s64[2][2]
  [
    [
        [0, 1],
        [2, 3]
    ]
    [
        [0, -1]
        [-2, -3]
    ]
  ]
  [
    [
        [4, 5],
        [6, 7]
    ]
    [
        [-4, -5],
        [-6, -7]
    ]
  ]
>
```

Note that in the suggested representation we also nest vectorized axes in a similar fashion to normal axes, with the difference that we don't add commas between different entries in each vectorized axis (perhaps we should add an empty line?).

Finally, we would have `Nx.shape(vec)` return the underlying shape:

```elixir
t = Nx.iota({3, 2, 1})
vec = vectorize(t, :vec)

Nx.shape(vec)
{2, 1}
```

## Implementation

The idea for implementing this would be to add a new field to the Nx.Tensor struct that keeps track of the vectorized axes. Then, each function that supports vectorization would have a wrapper code that turns the vectorized tensor into a normal higher dimensional tensor for the backend to operate on,
and then undoes this to obtain the output tensor.

Taking an example where we have different vectorized axes as inputs to Nx.add/2:

```elixir
vec1 = vectorize(Nx.iota({2, 2, 2}), :this)
vec2 = vectorize(Nx.iota({2, 2, 2}), :that)

# vec1 + vec2

# We detect that the vectorized axes are different and have a distinct total count of N=2.

# Now, we reshape each tensor to become non-vectorized. The left will have N-1 singleton axes added between the outermost vectorized axis and the inner non-vectorized:

t1 = Nx.reshape(vec1, {2, 1, 2, 2})

# Similarly, t2 will be reshaped to have the singleton dimensions added as outermost dimensions

t2 = Nx.reshape({1, 2, 2, 2})

# These shapes are now compatible in such a way that brocadcasting can happen normally. The actual algorithm for getting the binary operation shape will be a bit different to support overlapping axes, but this is the main idea.

# The output is then re-vectorized with the target axes as expected:

vectorize(t1 + t2, [:this, :that])
```

In this approach, the backends need to handle broadcasting, but don't need to know about vectorization in any way.

**Comment by polvalente** [comment]
Closing this discussion in favor of #1118, after the merge of #1115
