### ISSUE TITLE
Support Boolean-indexing

### ISSUE THREAD

**Issue by billylanchantin** [elixir-nx/nx#221]
## Background

See here for a reference on "Advance Indexing" in NumPy: https://numpy.org/doc/stable/reference/arrays.indexing.html#advanced-indexing

## Description

There are 2 types of advanced indexing in NumPy: integer-based and boolean-based. From my (cursory) reading of `Nx.slice/4`, integer-indexing is essentially covered. What I've not seen yet is boolean-indexing.

A common thing to do in NumPy is to access and/or manipulate an array based on some criteria. E.g.

```python
>>> import numpy as np
>>> a = np.arange(5)
array([0, 1, 2, 3, 4])
>>> b = a >= 3
array([False, False, False,  True,  True], dtype=bool)
>>> a[b]
array([3, 4])
>>> a[b] = 100
array([  0,   1,   2, 100, 100])
```

If you access an array `a` with a boolean array `b` (where `b`'s shape can be broadcast to `a`'s shape), NumPy knows to do things with elements of `a` whose corresponding element in `b` is `True`.

`Nx.select/3` seems to cover the result of doing `a[a >= 3]` fairly well (thanks for [pointing that out](https://elixir-lang.slack.com/archives/C01M2B96EF9/p1613583744229600), @seanmor5!). But the boolean-indexing counter part isn't there. I personally find boolean-indexing very powerful. IMO it's a type of de-functionalization for operations like select/replace, but with really powerful bonuses like being able to do boolean operations on the intermediate objects.

Is boolean-indexing something Nx could/should support? I'd be willing to try and implement it if so.

**Comment by seanmor5** [comment]
I think this would be generalized under something of a dynamic slicing API. `Nx.slice/4` covers slicing pretty well so far, (integer and range support), but we'd need to extend that to accept tensors. I think we could then resolve `a >= 3` to a tensor of indices and do the slicing that way. I think the binary implementation would be pretty straightforward, but the EXLA implementation might need something like [Gather](https://www.tensorflow.org/xla/operation_semantics#gather) or perhaps it could all be implemented in terms of `Nx.select/3`?

I'm for the addition of advanced/boolean-indexing. I think this is a good issue to gauge support from others as well.

**Comment by josevalim** [comment]
It is worth noting that at the moment we don't have a predicates type. I assume that would be a requirement for us to add this feature because otherwise it is impossible to know if we are passing a tensor of u8 to access certain positions or doing predicates.

We have been postponing adding predicates until we had a good use case, this may be it. :)

**Comment by elbow-jason** [comment]
WRT tensor slicing inside a `defn`:

I would find slicing with tensor's super useful.

While refactoring a codebase to use Nx, Mike Binns and I first tried to use slicing with a tensor only to discover that it was not (yet?) supported.

Because slicing with a tensor did not work we ended up struggling with the boundaries of defn vs def when we needed to slice.

The issue we were running into is that, and this could have been a code-design issue on our part, we wanted to dynamically slice using the value of a tensor, but inside the defn one cannot simply (as far as i know) say "evaluate the expression up to this point in the graph and give me the value".

We ended up getting away with a hack, since we knew that the slicing tensor we expected was a scalar with an int between 1 and 14 and the tensor-to-be-sliced was a `{14}` shaped tensor. We made a 15-branch cond (please forgive us!) with a transform on the each branch with a number literal:

```elixir
cond do
  Nx.equal(i, 0) -> transform(s, fn s -> s[0] end)
  # ...13
end
```

In the end, we ended up using a solution that used Nx.iota, Nx.select, and Nx.sum for the same effect.

Both solutions felt a little hacky.

**Comment by fire** [comment]
Can you post your resulting solution for other people to improve?

**Comment by billylanchantin** [comment]
> I think this would be generalized under something of a dynamic slicing API. Nx.slice/4 covers slicing pretty well so far, (integer and range support), but we'd need to extend that to accept tensors. I think we could then resolve `a >= 3` to a tensor of indices and do the slicing that way.

I think that approach will work! One concern I have is about how this composes. With booleans, I can do things like this:

```python
>>> import numpy as np
>>> a = np.arange(5)
>>> geq3 = a >= 3
>>> even = a % 2 == 0
>>> a[geq3 & even]
array([4])
```

If we're under-the-hood converting the booleans to tensors of indices, can we still do things like that? Not saying we can't, it's just not immediately obvious to me.

As per @elbow-jason's comment, it seems like accessing via tensors is useful regardless of the implications for this feature. We may want to break them apart into separate issues if we can't successfully couple them.

**Comment by seanmor5** [comment]
> If we're under-the-hood converting the booleans to tensors of indices, can we still do things like that? Not saying we can't, it's just not immediately obvious to me.

I think as @josevalim mentioned we'd need to support predicates. You can treat the resulting expression as a mask that uses select and maybe some other logic to do the "slicing". Or change the implementation of `Access` to always attempt to resolve expressions like `a[geq & even]` to indices. Then (if we add support for predicate), it would be a type check, so if the type is `:pred`, then we resolve that expression to indices to slice. If it's another type, we just treat the expression as indices and slice from there. Does that sound like it makes sense?

**Comment by josevalim** [comment]
FWIW, it seems that boolean indexing is not supported by JAX. It requires the boolean tensor to be concrete:

```
IndexError: Array boolean indices must be concrete.
>>> jax.make_jaxpr(jax.jit(lambda x: x[x>=3]))(np.array([1, 2, 3, 4, 5, 6]))
``` 

Looking at their issues tracker, they say:

> The problem here is that the shape of the output of thing[thing > 0] depends on the values in thing and changes for each run, while every array inside a jitted function needs to have a predictable shape (one of the optimizations XLA applies to jitted functions is pre-allocating all memory needed up front, and that requires knowing intermediate shapes at the time of invoking the function).

Which makes sense. If we can't compute the shape upfront, it will be very hard to optimize it. [They suggest to approach the problem differently](https://github.com/google/jax/issues/2765).

So I am thinking that, until we start supporting other compilers and we can have more insight if this is a good or bad idea, it is probably best to not support boolean indexing right now. We can support it, but I would do it via a explicit function and not really make it first class due to the pitfalls above.

> As per @elbow-jason's comment, it seems like accessing via tensors is useful regardless of the implications for this feature. We may want to break them apart into separate issues if we can't successfully couple them.

Yup. This is something very doable, the basic features are there, we just need to tackle it. :) Please open up a separate issue.

**Comment by josevalim** [comment]
For now, I suggest folks to tell us the exact problem that needs boolean indexing, and we can try to rewrite it into something that doesn't use it.

**Comment by elbow-jason** [comment]
@fire I put an example of put/at by index for rank == 1 tensors that works inside a defn in a gist: https://gist.github.com/elbow-jason/8541bdd034d5aae34a74b63c7d0b686c

**Comment by josevalim** [comment]
@elbow-jason I have created #223 for your case.

**Comment by seanmor5** [comment]
Following from the linked PyTorch paper, the way to approach this would be to define a `nonzero` function which creates a tensor of indices that are nonzero. And then use the indices tensor in conjunction with `Nx.take` to grab the values from the input tensor. `nonzero` would use the get/set dynamic dimension size capabilities of XLA to generate the bounded arrays.

**Comment by josevalim** [comment]
Closing as, per the above, it requires dynamic shapes :)
