### ISSUE TITLE
Introduce `log` macro in Nx Kernel

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/nx#245]
I was trying to debug a pretty complicated series of numerical definitions that we're getting stuck. My go-to in this instance is to just print debug and see where things are going wrong. I ended up writing a simple transform for logging that might prove useful for others:

```elixir
  defmacro log(level, msg, metadata \\ []) do
    quote do
      Nx.Defn.Kernel.transform(
        {unquote(level), unquote(msg), unquote(metadata)},
        fn {level, msg, metadata} -> Logger.log(level, msg, metadata) end
      )
    end
  end
```

I would personally support this getting added to `Nx.Defn.Kernel`, but I'm open to feedback. An alternative is just a simple `puts` implementation as well.

**Comment by seanmor5** [comment]
I think a short coming here is that calls to `log` get thrown out after the initial `defn` compilation.

**Comment by josevalim** [comment]
Yes, precisely. For the basic functionality that you want, we already have `inspect_expr`. But it would be nice to be able to log possible values. This is something I think we can implement once we are done with streams+outfeeds.

**Comment by elbow-jason** [comment]
Just to check my understanding here. To log values, I'm calling it `debug` here, without `Async` capabilities this would require the use of `debug` to work in one of these ways:

  + **Option 1** - `debug` creates a breaking point in the expression graph. Essentially this breaking point would split the operation into two parts - the operation before `debug` and the operation after `debug`. In the case of a native backend like EXLA, this would mean the operation-before part would be called like this `normal Elixir -> input into NIF -> execute operation -> output out of NIF -> normal Elixir` where each step is blocking/computationally-bound. Now that the operation-before is done we have a computed value that we can log/inspect/etc and then pass to the operation-after part that goes through the same cycle as the operation-before.

 + **Option 2** - `debug` calls a native function that logs the content of the computation.

### Potential Problems with Option 2

  + It might not exist for a backend.
  
  + If it is asynchronous and on-device (and since Async does not exist) we might not be able to synchronize the logging with the BEAM possibly leading to an apparent race-condition.
  
  + If it is (somehow) synchronous and on-device it's going to (somehow) block the device from resuming operation while it outputs to stdout.
  
  + If it is not on-device, but instead something like a native printf then that means we're back to something like option 1 except we are in C and not Elixir.
  
### Potential Problems with Option 1

  + It is slow (potentially very slow) - for native backends it results in at least 1 additional NIF crossing per call - for GPU-keep-on device calls it would mean also transferring the data off the GPU each `debug`.
  
### Option 3?

If I understand what is happening with `Async` correctly it means that we will be able to send work to a device and then, if we choose to, we can `await` that work. My question is: Will we be able to `await` that work such that we can get a value in the middle of a computation without blocking/interrupting the device? Would `await` give us the ability to implement a `debug` on the Elixir side without a significant cost in performance on the device/native side?

**Comment by josevalim** [comment]
So `async` is one of the steps towards streaming, which is coming next, and will allow us to get data in and out whenever we want. Once we have streaming, we can have logging by tagging some of the messages as special.

**Comment by josevalim** [comment]
Closing in favor of #556.
