### ISSUE TITLE
Encoding to_binary with `native` might become problematic

### ISSUE THREAD

**Issue by elbow-jason** [elixir-nx/nx#263]
This is probably not an issue yet, but if I understand what `64-native` in bitstrings means correctly it could be problematic later.

The binary encoding that Nx is currently using could potentially cause problems for someone sharing tensor data binaries between systems with different endianness. Unfortunately, I'm sure that decoding with a different endianness probably wouldn't fail and instead would just result in different numbers than were encoded.

I think [the call to :erlang.list_to_binary/1 on this line](https://github.com/elixir-nx/nx/blob/794734d70cffc2e76d13c471ab007d47d15f8d7a/nx/lib/nx.ex#L488) is the place where `native` endianness is happening.

We haven't seen this issue yet because people have not started building, recording, and sharing trained ML models in the ecosystem yet.

I can think of a few different ways to mitigate/minimize this potential issue:

### Choose to make Nx "always big" or "always little" encoding

We choose an endianness for all Nx binary representations.

### Put endianess info into binaries

We put "headers" on binaries to indicate endianness

### Warn the users

We tell users "If you are going to share binaries that represent tensors between systems you should include endianness information of the computer it came from"

### Add serialize/deserialize

If we add a serialize/deserialize we can give user's a guided path for sharing Nx binary data. We could include endianness, type, and shape info.

Thoughts?

**Comment by elbow-jason** [comment]
I personally prefer the serialize/deserialize option. 

Serialize could be as simple as:

```elixir
def serialize(tensor), do: :erlang.term_to_binary({native_endianness(), tensor})
```

**Comment by josevalim** [comment]
Correct. The encoding that we are using is for transfer between memory on the same machine. We don’t want to force a format because it means it is less efficient.l to do the work. For transfer between machines, then we need a mechanism to serialize and load data. Exactly option 2. However, before we invent our own mechanism, we need to see if there is prior art here.

also we can use term to binary because whoever is reading wants to read it back to native. Feel free to open a separate issue for the serializing. I will add a note that binary is in native.
