### ISSUE TITLE
Nx.to_heatmap/1 function should display an image resized to fit the screen

### ISSUE THREAD

**Issue by rnwatanabe** [elixir-nx/nx#383]
For large images the function displays an image that does not fit the screen. Below is an example. 

![image](https://user-images.githubusercontent.com/12960874/116483850-4b616b80-a85e-11eb-9473-f0c6ad0acc64.png)

The function should resize the image so as to the whole image  can be shown.

**Comment by seanmor5** [comment]
Thanks for pointing this out! My thoughts are that `to_heatmap` should not implicitly downsample. We could include downsampling options, but I'm not sure I like that either.

I would prefer an approach where we introduce a `resize` or `downsample` method similar to [jax.image.resize](https://jax.readthedocs.io/en/latest/_autosummary/jax.image.resize.html), but I'm not sure that belongs in the API either.

**Comment by rnwatanabe** [comment]
Another option would be to resize the  pixel as shown in screen so as to the whole image fit the screen.

**Comment by josevalim** [comment]
The issue here is really Livebook rendering it as ansi. Our goal is to support custom widgets in the future so we can render those as actual images, this way we will have more control. So I will close this for now, as IMO it is a Livebook issue rather than Nx one. :) We will get there. Thanks @rnwatanabe !
