### ISSUE TITLE
Be a target for m2cgen (too slow to compile huge file)

### ISSUE THREAD

**Issue by lucasavila00** [elixir-nx/nx#435]
I'm hacking around, trying to support Elixir (and Numeric Elixir) as a target for [m2cgen](https://github.com/BayesWitnesses/m2cgen).

m2cgen has a big test suite, and running this test suite on Regular Elixir is too slow.

I tried to use NX to speed things up, but NX takes too long to compile the files.

I have set up a little project which contains one model of the test suite, exported in Regular Elixir, and NX: https://github.com/lucasavila00/ex_m2cgen_examples

On regular Elixir, it takes ~3.5s to compile this file https://github.com/lucasavila00/ex_m2cgen_examples/blob/main/regular/script.ex

On NX, it takes ~18min to compile to compile this file https://github.com/lucasavila00/ex_m2cgen_examples/blob/main/numeric/lib/score.ex

I'm fully aware that from the compiler perspective this 15k lines file is madness. But at the same time, m2cgen is valuable tool, and smaller models exported with it do work fine in Elixir.

However, this 15k lines file is part of the test suite, and the Elixir target should run the test suite in a reasonable time in order to have support for it merged into m2cgen.

I'd be happy to help you in whatever way I can, please let me know if this is something you want to work on.

Thanks :)

**Comment by josevalim** [comment]
From a first glance, I don’t think Nx is a good target for m2cgen, exactly because Nx is designed to leverage high level information for optimizations and the tool has condensed the code into a low level in a way it would be hard for the backends to optimize it. In other words, Nx is meant to receive the model before you give it to m2cgen.

my suggestion is for you to see how to optimize the Elixir version. I believe you shouldn’t convert to map. Instead, your input should be an Elixir binary (a byte array) and you will read the values from the byte array with a small helper function. Those accesses should be in constant time.

Also, consider using cond to avoid some of the nesting, which should also make the compiler happier. Thanks for looking into this!

**Comment by josevalim** [comment]
Here is a more complete example of how you should handle the input and read from it:

```elixir
defmodule Bin do
  @compile {:inline, read: 2}
  def read(bin, pos) do
    <<_::size(pos)-unit(64)-binary, value::float, _::binary>> = bin
    value
  end
end

input = <<123.0::float, 456.0::float>>
Bin.read(input, 0)
Bin.read(input, 1)
```

The function `read` should be defined directly in the module. Note `float` here means double.

If you can compile the whole function into blogs of pattern matching, then even better. This:

```elixir
if (input[77]) > (0.5470938491933709) do
    if (input[35]) > (0.39695479786231147) do
        0.5363796312629354
    else
        0.5172166183018143
    end
    else
    if (input[156]) > (0.5119328420455852) do
        0.5204194764931365
    else
        0.499216952278257
    end
end
```

could be this:

```elixir
case input do
  <<_::size(77)-unit(64)-binary, value::float, _::binary>> when value > 0.5470938491933709 ->
    case input do
      <<_::size(35)-unit(64)-binary, value::float, _::binary>> when value > 0.39695479786231147 ->
        0.5363796312629354
      _ ->
        0.5172166183018143
    end

  <<_::size(156)-unit(64)-binary, value::float, _::binary>> when value > 0.5119328420455852 ->
    0.5204194764931365

  _ ->
    0.499216952278257
end
```

**Comment by lucasavila00** [comment]
Awesome, thanks for the tips :)
