### ISSUE TITLE
How do I check that a tensor equals a constant tensor in defn?

### ISSUE THREAD

**Issue by zacky1972** [elixir-nx/nx#496]
I'd like to check that a tensor placed out of `defp` equals a constant tensor in the `defp`, which is called by `defn` as follows:

```elixir
  defn match_fn(t) do
    transform(t, fn t -> match_sub(t) end)
  end

  defp match_sub(t) do
    c = Nx.tensor(1)

    if t == c do
      IO.puts("matched")
      t
    else
      IO.puts("unmatched")
      t
    end
  end
```

However, it doesn't work well:

```elixir
iex(18)> match_fn(Nx.tensor(1))
unmatched
#Nx.Tensor<
  s64
  1
>
```

@polvalente said "Could you be running into issues with having the defn compiler setting a different backend than the one you're using in the if condition?", then, I show them by IO.inspect:

```elixir
"t.data = %Nx.Defn.Expr{args: [0], context: :root, id: #Reference<0.2723978145.3456106503.157890>, op: :parameter}"
"Nx.tensor(1).data = %Nx.BinaryBackend{state: <<1, 0, 0, 0, 0, 0, 0, 0>>}"
unmatched
#Nx.Tensor<
  s64
  1
>
```

So I tried the following code:

```elixir
  defp match_sub(t) do
    c = Nx.tensor(1, backend: Nx.Defn.Expr)

    if t == c do
      IO.puts("matched")
      t
    else
      IO.puts("unmatched")
      t
    end
  end
``` 

However, it doesn't work because `t == c` inside the `defp`is strict equality.

Then, I tried the following code. but it doesn't still work well :

```elixir
  defp match_sub(t) do
    c = Nx.tensor(1, backend: Nx.Defn.Expr)

    if Nx.equal(t, c) == Nx.tensor(1, type: {:u, 8}, backend: Nx.Defn.Expr) do
      IO.puts("matched")
      t
    else
      IO.puts("unmatched")
      t
    end
  end
```

We felt this is an open issue.

**Comment by josevalim** [comment]
Hi @zacky1972! The thing you need to keep in mind is that `defn` does not work with tensors, it works with tensor expressions! So we execute the code inside `defn` and after we execute that, we evaluate the tensor expression (in the CPU, GPU, etc). So **you need to keep your code inside `defn` as much as possible**. This will work:

```elixir
  defn match_fn(t) do
    if t == 1 do
      t * 2
    else
      t / 2
    end
  end
```

You will see that, depending on the value of `t`, you will multiply by two or divide by two. However, doing `IO.puts` is not going to work in any case, because once again, `transform+IO.puts` will be called when we are building the expression, not when executing the code.

We actually want to add logging inside `defn`, but this feature is not yet supported. We will get there soon!

**Comment by zacky1972** [comment]
Thank you @josevalim 

I got an interesting execution result. The following code:

```elixir
  defn match_fn(t) do
    if t == 1 do
      transform(
        t,
        fn t ->
          IO.puts("matched")
          t
        end
      )
    else
      transform(
        t,
        fn t ->
          IO.puts("unmatched")
          t
        end
      )
    end
  end
```

generates the following results:

```elixir
iex> match_fn(1)
matched
unmatched
#Nx.Tensor<
  s64
  1
>
```

**Comment by josevalim** [comment]
Exactly. `transform` is executed when building the expressions. Think of it more like Elixir macros. Macros are expanded on both branches, because by expansion time we don't know which branch will be used.
