### ISSUE TITLE
Change Conv permutation configuration options

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/nx#543]
The current implementation is not really straightforward to use and is difficult to get right when configuring things like channels first vs. channels last convolution operations as with CNNs. Currently, we allow "permutations" on input and kernl and a final output permutation. It takes a lot of mental gymnastics to figure out how these permutations exactly map to how the convolution should be performed (I'm not even sure it's quiiiiite right in the Nx implementation). My proposal is to simplify the API with something that is closer to JAX. JAX uses a conv dimension numbers configuration that's created like:

```elixir
ConvDimensionNumbers('NCHW', 'IOHW', 'NCHW')
```

Where `NCHW` is read "batch size, channels, height, width" and `IOHW` is read "in channels, out channels, height, width".

What we need is a configuration option that gives information about:

- Where the batch dimension is in the input and output
- Where the channel dimension is in the input and output
- Where the spatial dimensions are on the input, output, and kernel (and how they align between input, kernel, and output, for example the binary backend expects height, width, depth, etc. to be aligned in all 3, so there would need to be some permuted dimensions to make things work). 
- Where the input channels are in the kernel
- Where the output channels are in the kernel

We have named axes, but using them would require us to force specific names to be able to use the conv operation. We could go the JAX route and have a configuration option that is a list of string configurations, but maybe that's too much. Any ideas?

**Comment by josevalim** [comment]
@seanmor5 my concern is that this configuration is then pretty image specific. Is conv only used for images? I can think of two options:

Have a `Nx.Image` module with image processing functionality where we can have a `Nx.Image.conv_options(...)` that would receive the configuration above and convert it to our current options, or we add the API above exclusively to Axon.

At the moment it is hard to discuss this because we don't know where Nx.Image would live and perhaps we want it outside of Nx. But we can also start it with it being in Nx and then extract later if necessary?

**Comment by seanmor5** [comment]
This ended up not being an issue for me in implementing conv configurations in Axon. I will close for now.
