### ISSUE TITLE
[Question/Discussion] Complex number support in Elixir

### ISSUE THREAD

**Issue by polvalente** [elixir-nx/nx#704]
Forgive me for going offtopic but, I believe that we have complex number support via Pol Valente's elixir-complex. Should not complex number support be added to Elixir (pure elixir implementation) or even OTP (C implementation) itself? Some languages that have built-in complex numbers support are:

- Python
- Ruby
- Perl
- Haskell
- OCaml
- Golang
- Rust
- C
- C++

Of course I found languages that don't have built in implementations like:

- Java
- Clojure
- Scala
- Kotlin
- Javascript

Is there any particular reason why we choose do be in the latter? Shouldn't we encourage the use of a standard complex numbers implementation, rather than multiple complex number packages?

_Originally posted by @Benjamin-Philip in https://github.com/elixir-nx/nx/issues/695#issuecomment-1081661186_

**Comment by mlliarm** [comment]
Hello,

To add to the discussion one more language (from the array family), [jlang](https://www.jsoftware.com/#/) has also built-in complex numbers support, and so does Fortran since 1977 at least.

If the Elixir community would like Elixir to be able to take up scientific computing tasks as well, the complex arithmetic should be built-in the language (or OTP), imho. Surely, complex numbers are not being used (afaik) in ML/DL that are trendy now, but they are useful constructs for calculating roots of nonlinear algebraic equations. Differential equations get reduced to such algebraic equation solving problems, and it can happen that the roots are imaginary or complex. 

So, if you'd like Elixir to be a language that can, like jlang (or python or julia or ...), be used for mathematical modelling and computational physics, it should belong to the 1st category of languages. Unless if the Elixir community wishes it to remain in the web-dev languages group. If the purpose of Elixir (and Erlang) are for serving reliable systems, then I guess it won't hurt if the complex numbers feature remain as an external library.

Best,
Mike

**Comment by josevalim** [comment]
The current Elixir guidelines for adding new features would not support adding Complex to Elixir, because it is not something needed in core or something that would substantially benefit from being in core. There are some features, like guards, that would not support Complex and make it feel a bit awkward to be in core.

However, Elixir was designed to be an extensible language and we can add mechanism necessary to make Complex more first class, even without making it part of the language. So I am confident we can make the Complex library a standard in the ecosystem, like Decimal became an standard for decimal numbers.
