### ISSUE TITLE
Add a function to add names to an existing tensor

### ISSUE THREAD

**Issue by kipcole9** [elixir-nx/nx#816]
### Request

* Add a function to add names to an existing tensor

### Background

I'm working on interoperability between [Vix](https://github.com/akash-akya/vix). Until `Nx` supports zero-copy I'm using `Nx.from_binary/2`. However this doesn't support a `:names` option and there doesn't appear to be a function to add `:names` to an existing tensor.

**Comment by josevalim** [comment]
You typically call Nx.reshape after from_binary. The names option is supported there. :)

**Comment by kipcole9** [comment]
Feeling very stupid, I am calling 'Nx.reshape/2` but did not see the `:names` option. Sorry for the noise.

**Comment by josevalim** [comment]
No worries, I asked myself the same question when I added from_binary to StbImage. Also note Nx should probably be an optional dependency, so on Elixir main (upcoming v1.14) you can use `mix compile --no-optional-deps` to make sure the project compiles without it, otherwise it is easy to sneak a bug. And include that on CI once Elixir is released. :D
