### ISSUE TITLE
Add weighted_mean function

### ISSUE THREAD

**Issue by msluszniak** [elixir-nx/nx#937]
I think it will be helpful if we add an option `:sample_weights`. It will default to `nil` and then it will calculate the arithmetic mean. Otherwise, it will calculate the weighted mean. We can add the analogical functionality to `Nx.mean`.

**Comment by msluszniak** [comment]
I could implement this functionality.

**Comment by polvalente** [comment]
Can't we just use Nx.multiply in combination with Nx.mean for that functionality?

**Comment by polvalente** [comment]
Another option would be to add another function, Nx.weighted_mean that receives a data tensor and the weights tensor, but it would just be what I suggested with Nx.multiply.

I don't think we can a tensor as an option due to closures, and having it as an optional argument would make for a worse interface on Nx.mean (one would have to call Nx.mean(tensor, 1, opts) to use options)

**Comment by msluszniak** [comment]
I agree that implementing this as an option for `Nx.mean` might not be the best. But in Numpy there are functions like [mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html) and [average](https://numpy.org/doc/stable/reference/generated/numpy.average.html). Mean is just classic arithmetic mean. Average implements weighted mean. I think that implementing a separate function for `Nx.sum(x * weights, axes: axes) / Nx.sum(weights, axes: axes)`  will help a little bit, since this operation is very common.

**Comment by josevalim** [comment]
I am in favor of adding an `average` function (or `weighted_mean`) that expects weights. :+1:
