### ISSUE TITLE
Grad for Nx.select(Nx.is_nan, ...)

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/nx#973]
```elixir
Mix.install(
  [
    {:nx, "~> 0.4.0"},
    {:exla, "~> 0.4.0"}
  ],
  config: [
    nx: [
      default_backend: EXLA.Backend,
      default_defn_options: [compiler: EXLA]
    ]
  ]
)
defmodule T do
  import Nx.Defn

  defn g(t) do
    grad(t, &fun(&1))
  end

  defn fun(t) do
    # t1 = t       # grad returns 0.0
    t1 = t / t   # grad returns NaN
    Nx.select(Nx.is_nan(t1), 0.0, t1)
  end
end

t = Nx.tensor(:nan)
T.g(t)
```

```
#Nx.Tensor<
  f32
  EXLA.Backend<host:0, 0.3344788769.4006215744.210670>
  NaN
>
```

I expect both variants (`t1 = t` and `t1 = t / t`) returns 0.0
Maybe I misunderstand something?

**Comment by polvalente** [comment]
That's a great question with an interesting answer!

Although the numbers fed into Nx.select are the same, we have to keep in mind that there's an extra operation (the division) on the execution graph.

This means that the grad for select will the multiply the grad for divide. Since the value fed into divide is NaN, it's grad is NaN, and NaN * 0 (the grad for select) is NaN as well.

On one hand, we could probably treat this special case of t/t becoming 1.

On the other hand, we can also think mathematically about it, in the sense that if t is unknown it can be 0, and being 0 we can't actually simplify the division. This in turn means that if NaN, 0 or ±Inf is fed into the division the output will be NaN.

If you took the division out of the function of which you're taking the grad, I'd expect it all to work correctly, returning 0.
